#!/usr/bin/env python3
from __future__ import annotations
import copy, hashlib, json
from collections import Counter
from pathlib import Path

SRC=Path('validation_temp/20260905-r1/materialize_r3.py')
exec(compile(SRC.read_text(encoding='utf-8'),str(SRC)+'[R4_FULL_STAGE_A]','exec'),{'__name__':'__main__','__file__':str(SRC)})

ROOT=Path('runs/2026-09-07/r7-20260905-production-r1')
A=ROOT/'stages/stage-a.json'
Q=ROOT/'stage-0-7c.json'
p=json.loads(A.read_text(encoding='utf-8'))
strict=copy.deepcopy(p['strict_passed_spec'])

CANONICAL_STAGE_B_NOTE=(
    'Stage B must verify the provided source-candidate URL and build a valid evidence package before drafting. '
    'This Stage A spec is not evidence_complete, and primary_url is not evidence by itself.'
)

# Complete the frozen-V3 compatibility surface only with bounded Stage-A metadata.
for item in strict:
    item['stage_b_requirement_note']=CANONICAL_STAGE_B_NOTE
    if 'policy_regulatory_anchor' in item.get('anchor_classes',[]):
        if item['spec_id']=='STD26_R8_006':
            item.update({
                'legal_instrument_type':'Utah tax-increment incentive approval resolution',
                'competent_authority':'Utah Inland Port Authority',
                'procedural_status':'approved incentive resolution',
                'adoption_date':'2026-09-03',
                'publication_date':'2026-09-03',
                'effective_date':'2026-09-03',
                'mandatory_application_date':'not_applicable_voluntary_project_incentive',
                'affected_entities':['Anson Resources Green River lithium project'],
                'affected_products_or_activities':['Green River lithium project development'],
                'geographic_scope':'Utah, United States',
                'extraterritorial_effect':'none established by current Stage A source',
                'budget_or_funding_source':'tax increment generated by the approved project area structure',
                'implementation_mechanism':'approved use of tax increment under UIPA incentive resolution',
                'administrative_readiness':'resolution approved; downstream reimbursement and project execution remain future-stage checks',
                'exemptions_and_thresholds':[],
                'transition_and_grandfathering':[],
                'noncompliance_consequences':[],
                'appeal_or_litigation_risk':'not established by current Stage A source',
                'reversibility_risk':'future administrative or project conditions remain to be verified at Stage B and follow-up',
                'precedent_scope':'project-specific incentive approval; no market-wide rule claimed',
                'legal_policy_transmission_chain':['UIPA resolution approval','tax-increment incentive availability','project development execution'],
                'next_implementation_trigger':'project execution and any documented incentive reimbursement milestone',
            })
        elif item['spec_id']=='STD26_R8_009':
            item.update({
                'legal_instrument_type':'public subsidy call implementation',
                'competent_authority':'Croatia Environmental Protection and Energy Efficiency Fund (FZOEU)',
                'procedural_status':'application window opened',
                'adoption_date':'2026-07-24',
                'publication_date':'2026-07-24',
                'effective_date':'2026-09-02',
                'mandatory_application_date':'not_applicable_voluntary_subsidy_program',
                'affected_entities':['eligible Croatian households under the public call'],
                'affected_products_or_activities':['home battery storage','solar power plants','heat pumps'],
                'geographic_scope':'Croatia',
                'extraterritorial_effect':'none established by current Stage A source',
                'budget_or_funding_source':'EUR 38 million public-call program announced by FZOEU',
                'implementation_mechanism':'electronic applications through the eFZOEU information system',
                'administrative_readiness':'applications accepted from 2026-09-02 09:00 through eFZOEU',
                'exemptions_and_thresholds':[],
                'transition_and_grandfathering':[],
                'noncompliance_consequences':[],
                'appeal_or_litigation_risk':'not established by current Stage A source',
                'reversibility_risk':'program funding availability and administrative award decisions remain follow-up points',
                'precedent_scope':'Croatia household support program; no EU-wide applicability claimed',
                'legal_policy_transmission_chain':['FZOEU public call','application opening','administrative award and supported installation'],
                'next_implementation_trigger':'award decisions, committed funding, and verified supported battery installations',
            })

story_ids=[]
for item in strict:
    story_ids.extend(item['source_story_ids'])
assert len(story_ids)==len(set(story_ids))==11, story_ids

anchors=Counter(a for item in strict for a in item.get('anchor_classes',[]))
lenses=Counter(a for item in strict for a in item.get('structural_value_lenses',[]))
classes=Counter(item.get('decision_value_classification') for item in strict if item.get('decision_value_classification'))
route_counts=Counter(item.get('selection_route') for item in strict if item.get('selection_route'))
critical=[item['spec_id'] for item in strict if item.get('decision_value_classification')=='critical_structural']
high=[item['spec_id'] for item in strict if item.get('decision_value_classification')=='high_decision_value']
follow=[item['spec_id'] for item in strict if item.get('baseline_follow_up_relation') not in (None,'','new','new_unrelated','unrelated','not_applicable','none')]
tech_gaps=[item['spec_id'] for item in strict if 'technology_commercialization_anchor' in item.get('anchor_classes',[]) and isinstance(item.get('technology_validation_gap'),str) and item.get('technology_validation_gap').strip()]
legal_gaps=[item['spec_id'] for item in strict if 'policy_regulatory_anchor' in item.get('anchor_classes',[]) and item.get('legal_policy_stage') not in {
    'stage_0_rhetoric_or_advocacy','stage_1_roadmap_consultation_or_draft_standard','stage_2_bill_or_proposed_rule',
    'stage_3_enacted_law_final_rule_or_adopted_standard','stage_4_implementation_budget_guidance_or_registry',
    'stage_5_enforcement_payment_denial_penalty_or_recall','stage_6_judicial_or_tribunal_interpretation'}]

policy_file=Path('docs/STRUCTURAL_NEWS_VALUE_SELECTION.md')
prompt_file=Path('docs/llm_prompts/v1/01_PROMPT_0_1_Stage_A.md')
sha=lambda path: hashlib.sha256(Path(path).read_bytes()).hexdigest()
active_docs=[
    'docs/llm_prompts/v1/01_PROMPT_0_1_Stage_A.md',
    'docs/FACT_DISCIPLINE.md',
    'docs/PROMPT_ABC_DEFAULT_MODE.md',
    'docs/FUTURE_CARD_STANDARD_FULL_SCHEMA.md',
    'docs/CARD_ID_STANDARD.md',
    'docs/WORKFLOW.md',
    'docs/OPERATIONS.md',
    'docs/POST_ACCEPTANCE_CONTENT_ENRICHMENT_QC.md',
    'docs/RELATED_LIFECYCLE_CONTRACT.md',
]
for path in active_docs:
    assert Path(path).exists(), path

ledger=[]
for item in strict:
    merged=set(item.get('merged_story_ids') or [])
    for story_id in item['source_story_ids']:
        row={
            'story_id':story_id,
            'anchor_classes':copy.deepcopy(item.get('anchor_classes',[])),
            'news_value_basis':item['changed_judgment'],
            'structural_value_lenses':copy.deepcopy(item.get('structural_value_lenses',[])),
            'structural_value_override_applied':item.get('structural_value_override_applied',False),
            'structural_value_override_reason':item.get('structural_value_override_reason'),
            'evidence_needed_for_stage_b':copy.deepcopy(item['evidence_needed_for_stage_b']),
            'why_execution_event_not_required':item.get('why_execution_event_not_required'),
            'incremental_information':item['incremental_information'],
            'decision_relevance':item['decision_relevance'],
            'baseline_expectation_changed':item['baseline_expectation_changed'],
            'follow_up_relation':item.get('baseline_follow_up_relation','new_unrelated'),
            'next_confirmation_points':copy.deepcopy(item['next_confirmation_points']),
            'portfolio_coverage_contribution':copy.deepcopy(item.get('portfolio_coverage_contribution',[])),
            'earnings_deep_dive_required':item.get('earnings_deep_dive_required',False),
            'qna_status':item.get('qna_status','not_applicable'),
            'review_pool_subtype':'not_applicable_strict',
            'review_pool_repromotion_precondition':'not_applicable_strict',
            'decision_news_value_score':item['decision_news_value_score'],
            'decision_value_breakdown':copy.deepcopy(item['decision_value_breakdown']),
            'decision_value_classification':item['decision_value_classification'],
            'prior_state':item['prior_state'],
            'new_verified_fact':item['new_verified_fact'],
            'changed_judgment':item['changed_judgment'],
            'uncertainty_resolved':item['uncertainty_resolved'],
            'remaining_uncertainty':item['remaining_uncertainty'],
            'denominator_used':item.get('denominator_used','Named event/program only.'),
            'denominator_gap':item.get('denominator_gap'),
            'publication_urgency':copy.deepcopy(item['publication_urgency']),
            'anti_bias_check':copy.deepcopy(item['anti_bias_check']),
            'structural_rescue_required':item.get('structural_rescue_required',False),
            'structural_rescue_question':item.get('structural_rescue_question'),
            'technology_validation_stage':item.get('technology_validation_stage','not_applicable'),
            'technology_score_cap_applied':item.get('technology_score_cap_applied',False),
            'technology_validation_gap':item.get('technology_validation_gap','not_applicable'),
            'legal_policy_stage':item.get('legal_policy_stage'),
            'ledger_decision':'merged' if story_id in merged else 'passed',
            'editorial_bucket':'strict_passed_spec',
            'spec_id':item['spec_id'],
        }
        ledger.append(row)

summary={
    'legacy_keep_count':0,
    'strict_passed_spec_count':len(strict),
    'needs_review_count':0,
    'candidate_review_pool_count':0,
    'watchlist_context_pool_count':0,
    'reject_or_support_only_pool_count':0,
    'rejected_count':0,
    'existing_reinforcement_count':0,
    'support_source_only_count':0,
    'duplicate_or_reinforcement_count':0,
    'stale_discarded_count':0,
    'stale_warm_review_count':0,
    'total_ledger_count':len(ledger),
    'ledger_matches_story_count':True,
    'structural_selector_policy_version':'STRUCTURAL_NEWS_VALUE_SELECTION_V3',
    'structural_selector_policy_file':'docs/STRUCTURAL_NEWS_VALUE_SELECTION.md',
    'structural_selector_policy_sha':sha(policy_file),
    'credibility_cardability_value_urgency_separated':True,
    'industry_first_weighting_applied':True,
    'core_industrial_weight_total':70,
    'multi_anchor_class_model_applied':True,
    'mandatory_structural_lenses_applied':True,
    'anchor_class_counts':dict(sorted(anchors.items())),
    'structural_lens_coverage_counts':dict(sorted(lenses.items())),
    'decision_value_classification_counts':dict(sorted(classes.items())),
    'critical_structural_candidate_ids':critical,
    'high_decision_value_candidate_ids':high,
    'high_value_review_pool_ids':[],
    'structural_signal_review_pool_ids':[],
    'earnings_deep_dive_pool_ids':[],
    'follow_up_candidate_ids':follow,
    'zero_coverage_domains':[],
    'execution_or_formality_bias_findings':[],
    'technology_validation_gap_ids':tech_gaps,
    'legal_policy_stage_gap_ids':legal_gaps,
    'search_before_delete_applied':True,
    'earnings_call_qna_rule_applied':True,
    'follow_up_probability_review_applied':True,
    'portfolio_coverage_audit_applied':True,
    'structural_value_selector_status':'PASS',
    'portfolio_coverage_audit_status':'PASS',
    'earnings_call_qna_audit_status':'NOT_APPLICABLE',
    'follow_up_repromotion_audit_status':'PASS',
    'execution_event_bias_audit_status':'PASS',
    'content_depth_audit_status':'PASS',
    'decision_ledger_count':len(ledger),
    'selection_route_counts':dict(sorted(route_counts.items())),
    'formal_event_count':len(strict),
    'source_bound_observation_count':len(ledger),
}

full={
    'stage':'stage_a',
    'status':'PASS',
    'run_id':p['run_id'],
    'base_main_commit_sha':p['base_main_commit_sha'],
    'base_full_blob_sha':p['base_full_blob_sha'],
    'run_tag':'20260907_R8_SEP5_PRODUCTION9_STAGE_A_COMPOSITE',
    'run_label':'Sep 5 R8 production9 Stage A composite from machine-adjudicated strict candidates; full discovery accounting remains in Stage 0.0C.',
    'source_prompt_file':str(prompt_file),
    'source_prompt_sha256':sha(prompt_file),
    'source_prompt_version':'STAGE_A_INTEGRATED_SELECTOR_V4_20260901',
    'source_prompt_authority':'repo_source_file_prompt',
    'source_prompt_provenance_status':'PASS',
    'selection_policy_version':'EMBEDDED_NEWS_VALUE_SELECTION_V4',
    'input_file':str(ROOT/'stage-0-0c.json'),
    'baseline_file':'data/cards.full.json',
    'baseline_source_declaration':f'current main {p["base_main_commit_sha"]}; canonical blob {p["base_full_blob_sha"]}; 1569 cards',
    'baseline_count':1569,
    'github_main_sync_required_later':False,
    'source_universe':f'{len(ledger)} source observations / {len(strict)} final strict Stage A specs filtered from the fully-accounted 0.0C discovery universe.',
    'story_count':len(ledger),
    'event_count':len(strict),
    'original_status_counts':{'KEEP':len(ledger)},
    'integrity_summary':{
        'status':'PASS',
        'main_sha':p['base_main_commit_sha'],
        'canonical_blob_sha':p['base_full_blob_sha'],
        'production_strict_event_count':len(strict),
        'production_source_observation_count':len(ledger),
        'duplicate_event_membership':0,
        'unassigned_event_membership':0,
        'coverage_discovery_ref':str(ROOT/'stage-0-0c.json'),
    },
    'recommended_for':['Stage B evidence package construction for strict_passed_spec[] only'],
    'stage_a_validity_status':'PASS',
    'artifact_consistency_status':'PASS',
    'csv_schema_status':'PASS',
    'review_pool_partition_status':'PASS',
    'strict_pass_gate_metadata_status':'PASS',
    'baseline_duplicate_screen_status':'PASS',
    'review_pool_carry_forward_ledger_status':'PASS',
    'next_call_recommendation':{
        'recommended_next_call':'Stage B r0',
        'recommended_prompt_id':'Prompt 0.2',
        'recommended_input_universe':'Stage A strict_passed_spec[] only',
        'reason':f'{len(strict)} strict candidates are formal production-chain inputs; non-strict discovery rows remain terminally accounted in 0.0C.',
        'blocked_items_summary':[],
    },
    'required_docs_check':{
        'docs_expected':active_docs,
        'docs_read_from_github_main':active_docs,
        'docs_missing_or_unreadable':[],
        'status':'PASS',
        'authority_note':'Integrated Stage A V4 is active authority; retired V3 policy/addendum bodies are private compatibility projection only.',
    },
    'lane_sanity_rules_applied':[
        'source_bound_observation_identity','current_main_event_duplicate_gate_pass','rescue_before_delete',
        'V4_score_caps_machine_checked','0_0C_full_discovery_accounting_preserved','production_composite_strict_only',
    ],
    'dropped_treasure_hunt':{
        'performed':False,
        'trigger_reason':'0.0C discovery and rescue were locked upstream; production Stage A composite performs no new search.',
        'sample_strategy':'not_applicable_at_production_composite',
        'sample_size':0,
        'sampled_story_ids':[],
        'rescued_count':0,
        'rescue_ids':[],
        'non_sampled_dropped_count':0,
        'non_sampled_ledger_policy':'Every production-composite source observation is represented exactly once in decision_ledger; full non-strict accounting remains in 0.0C.',
    },
    'summary':summary,
    'legacy_keep':[],
    'strict_passed_spec':strict,
    'candidate_review_pool':[],
    'watchlist_context_pool':[],
    'reject_or_support_only_pool':[],
    'review_pool':[],
    'dropped_treasure_hunt_result':[],
    'rejected':[],
    'existing_reinforcement':[],
    'support_source_only':[],
    'review_pool_resolution_ledger':[],
    'decision_ledger':ledger,
    'accounting':{
        'input_source_observations':len(ledger),
        'strict_source_observations':len(ledger),
        'strict_passed_events':len(strict),
        'non_strict_source_observations':0,
        'unaccounted':0,
        'upstream_0_0c_expanded_universe_count':394,
    },
}

A.write_text(json.dumps(full,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
# Stage A bytes changed, so refresh only the 0.7C byte-freeze binding. Downstream
# content does not embed the Stage A artifact hash; operation bytes remain fixed.
q=json.loads(Q.read_text(encoding='utf-8'))
q['hash_chain']['stage_a']=sha(A)
Q.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('RESULT: PASS_R4_FULL_STAGE_A_COMPOSITE')
print('STORY_COUNT',len(ledger),'EVENT_COUNT',len(strict))
print('STAGE_A_SHA',sha(A))
