import fs from 'node:fs';

const finalQcPath = 'docs/llm_prompts/v1/09_PROMPT_0_7_Final_QC.md';
const testPath = 'validation_scripts/tests/test_workflow_contracts.py';

let finalQc = fs.readFileSync(finalQcPath, 'utf8');
const oldBlock = `For every format-risk \`publish_ready[]\` item, the following route fields are mandatory and must be copied from the same-run Content Polish / Evidence QC lineage without alteration:\n\n- \`selected_anchor_path: execution|v3_non_execution\`\n- \`anchor_path_qc_passed: true\`\n- \`execution_anchor_qc_status: pass|not_applicable\`\n- \`structural_value_override_qc_status: pass|not_applicable\`\n- \`non_applicable_anchor_path_reason\`\n\nExactly one route status must be \`pass\`; the other must be \`not_applicable\` with a specific reason. Missing, contradictory, dual-pass, or dual-not-applicable route metadata requires \`final_qc_hold\` or return to the earliest defective stage and must not enter \`publish_ready[]\`.\n`;
const newBlock = `For every format-risk \`publish_ready[]\` item, the following route fields are mandatory and must be copied from the same-run Content Polish / Evidence QC lineage without alteration:\n\n- \`selected_anchor_path: execution|v3_non_execution\`\n- \`anchor_path_qc_passed: true\`\n- \`execution_anchor_qc_status: pass|not_applicable\`\n- \`structural_value_override_qc_status: pass|not_applicable\`\n- \`non_applicable_anchor_path_reason\`\n\nExactly one route status must be \`pass\`; the other must be \`not_applicable\` with a specific reason. Missing, contradictory, dual-pass, or dual-not-applicable route metadata requires \`final_qc_hold\` or return to the earliest defective stage and must not enter \`publish_ready[]\`.\n\nFor every format-risk \`publish_ready[]\` item with \`selected_anchor_path = v3_non_execution\`, preserve the complete same-run, source-backed Structural Value Override package byte-for-byte alongside the route fields:\n\n- \`structural_value_override_applied: true\`\n- non-empty valid \`anchor_classes[]\`\n- non-empty item-specific \`evidence_needed_for_stage_b[]\`\n- specific \`why_execution_event_not_required\`\n- \`prior_state\`\n- \`new_verified_fact\`\n- \`changed_judgment\`\n- applicable uncertainty / probability-change fields\n- applicable baseline-expectation / before-after fields\n- current-run source lineage that supports each package field\n\nThese fields must remain available to Prompt 0.8 and must not be summarized away, reconstructed from memory, or dropped by Final QC. If any required V3 package field is missing, altered, generic, unsupported, or inconsistent with the selected route, route the item to \`final_qc_hold\` or \`needs_return_to_evidence_qc\`; do not emit it in \`publish_ready[]\`.\n`;
if (!finalQc.includes(oldBlock)) throw new Error('Final QC route block not found');
finalQc = finalQc.replace(oldBlock, newBlock);
fs.writeFileSync(finalQcPath, finalQc);

let tests = fs.readFileSync(testPath, 'utf8');
const marker = '\n\nif __name__ == "__main__":\n    unittest.main()';
const testMethod = `\n\nclass FinalQcV3PackageContractTest(unittest.TestCase):\n    def test_final_qc_preserves_complete_v3_package_for_publish_ready(self):\n        prompt = (ROOT.parent / "docs/llm_prompts/v1/09_PROMPT_0_7_Final_QC.md").read_text(encoding="utf-8")\n        required = [\n            "selected_anchor_path = v3_non_execution",\n            "structural_value_override_applied: true",\n            "anchor_classes[]",\n            "evidence_needed_for_stage_b[]",\n            "why_execution_event_not_required",\n            "prior_state",\n            "new_verified_fact",\n            "changed_judgment",\n            "must remain available to Prompt 0.8",\n        ]\n        for token in required:\n            self.assertIn(token, prompt)\n`;
if (!tests.includes('class FinalQcV3PackageContractTest')) {
  if (!tests.includes(marker)) throw new Error('unittest main marker not found');
  tests = tests.replace(marker, testMethod + marker);
  fs.writeFileSync(testPath, tests);
}
