from __future__ import annotations

import copy
import hashlib
import io
import unittest
from contextlib import redirect_stdout
from pathlib import Path

from validation_scripts import stage_lineage_contract_check as lineage
from validation_scripts.tests.test_stage_a_v3_route_alignment import (
    TestStageAV3RouteAlignment,
)


class TestStageAFullV3ArtifactCompleteness(unittest.TestCase):
    MANDATORY_DOCS = [
        "docs/FACT_DISCIPLINE.md",
        "docs/STRUCTURAL_NEWS_VALUE_SELECTION.md",
        "docs/llm_prompts/v1/01A_PROMPT_0_1S_Structural_Value_Override.md",
        "docs/PROMPT_ABC_DEFAULT_MODE.md",
        "docs/PROMPT_ABC_SUPPORTING_RULES.md",
        "docs/FUTURE_CARD_STANDARD_FULL_SCHEMA.md",
        "docs/CARD_ID_STANDARD.md",
        "docs/WORKFLOW.md",
        "docs/OPERATIONS.md",
        "docs/POST_ACCEPTANCE_CONTENT_ENRICHMENT_QC.md",
    ]
    SOURCE_PROMPT_FILE = "docs/llm_prompts/v1/01_PROMPT_0_1_Stage_A.md"
    SOURCE_PROMPT_SHA256 = hashlib.sha256(
        (Path(__file__).resolve().parents[2] / SOURCE_PROMPT_FILE).read_bytes()
    ).hexdigest()

    def full_spec(self):
        spec = copy.deepcopy(TestStageAV3RouteAlignment().execution_spec())
        spec.update(
            {
                "source_origin": "final_news_llm_input.stories",
                "merge_status": "single_story",
                "merged_story_ids": [],
                "region": "GLOBAL",
                "representative_date": "2026-08-15",
                "representative_source": "example.com",
                "source_tier_estimate": "tier_1",
                "cat": "technology",
                "sub_cat": "commercialization",
                "signal_estimate": "material",
                "signal_rubric_estimate": {"status": "material"},
                "strategic_lens": ["technology_transition_commercialization"],
                "primary_url": "https://example.com/story",
                "urls": ["https://example.com/story"],
                "event_anchor": "production_start",
                "strict_pass_gate": {
                    "status": "pass",
                    "reason": "The current production-start state satisfies the strict selector gate.",
                    "all_six_conditions_passed": True,
                    "anchor_supported_by_upstream_text": True,
                    "why_not_review_pool": "The upstream text identifies a current production-start event with bounded Stage B verification targets.",
                },
                "source_cluster_preserved": True,
                "source_diversity_path": {
                    "status": "viable",
                    "reason": "The representative source and linked support candidates remain available for Stage B verification.",
                },
                "support_source_candidates_accounted": True,
                "title_raw": "Synthetic production-start event",
                "summary_hint": "A named product has moved from roadmap status to production start.",
                "context_text": "Synthetic full-artifact regression context for a production-start event.",
                "why_now": "The manufacturing stage has changed from future roadmap to current execution.",
                "market_relevance": "The stage change affects commercialization timing and customer availability assessment.",
                "source_priority_notes": "Stage B must verify the company filing and production-start date.",
                "upstream_labels": {
                    "triage_status": "kept",
                    "matched_buckets": ["technology"],
                    "drop_reason": None,
                    "integrity_group_id": "SYNTHETIC_GROUP_001",
                    "integrity_is_best": True,
                    "drop_reason_overridden": False,
                },
                "staleness": {
                    "event_date": "2026-08-15",
                    "publication_date": "2026-08-15",
                    "staleness_gap_days": 0,
                    "staleness_suspected": False,
                    "fresh_followup": False,
                    "staleness_override": False,
                    "decision": "current",
                },
                "needs_review": False,
                "review_reason": None,
                "stage_b_requirement_note": (
                    "Stage B must verify the provided source-candidate URL and build a valid evidence package before drafting. "
                    "This Stage A spec is not evidence_complete, and primary_url is not evidence by itself."
                ),
                "execution_credibility_gate": {
                    "status": "PASS",
                    "anchor_type": "production_start",
                    "anchor_strength": "strong",
                    "stage_precision_note": "The upstream Stage A material identifies a current production-start state.",
                },
                "independent_cardability_gate": {
                    "status": "PASS",
                    "distinct_event_or_stage_progression": True,
                    "full_schema_viability": "PASS",
                    "duplicate_or_reinforcement_note": "The production-start event is distinct from the prior roadmap state.",
                },
                "decision_news_value_score": 58,
                "decision_value_breakdown": {
                    "market_structure_competition": 15,
                    "supply_demand_price_utilisation": 15,
                    "technology_performance_safety": 12,
                    "cashflow_asset_value": 5,
                    "law_policy_market_access": 5,
                    "systemic_scale": 2,
                    "persistence_irreversibility": 2,
                    "decision_urgency_actionability": 2,
                },
                "decision_value_classification": "material_industry_signal",
                "structural_value_lenses": ["technology_transition_commercialization"],
                "denominator_used": "Named production program; no broader market-share denominator is claimed.",
                "denominator_gap": False,
                "publication_urgency": {
                    "level": "near_term",
                    "action_required": "Reassess commercialization timing and customer-availability assumptions for the named product.",
                    "decision_deadline": None,
                },
                "baseline_follow_up_relation": "new_unrelated",
                "portfolio_coverage_contribution": ["technology_transition_commercialization"],
                "earnings_deep_dive_required": False,
                "earnings_release_available": "not_applicable",
                "ir_deck_available": "not_applicable",
                "call_or_transcript_expected": "not_applicable",
                "qna_status": "not_applicable",
                "prior_period_comparison_required": False,
                "earnings_rescue_questions": [],
                "anti_bias_check": {
                    "binding_status_used_as_importance_proxy": False,
                    "legal_formality_used_as_importance_proxy": False,
                    "headline_amount_used_without_denominator": False,
                    "announced_capacity_treated_as_actual_output": False,
                    "routine_execution_event_overranked": False,
                    "conventional_execution_event_required_without_reason": False,
                },
                "structural_rescue_required": False,
                "structural_rescue_question": None,
                "search_before_delete_status": "applied",
                "technology_validation_stage": "production_start",
                "technology_score_cap_applied": False,
                "technology_validation_gap": "Named customer shipment volume remains unverified at Stage A.",
            }
        )
        return spec

    def ledger_row(self, spec):
        return {
            "story_id": spec["source_story_ids"][0],
            "upstream_status": "kept",
            "upstream_drop_reason": None,
            "headline": "Synthetic production-start event",
            "site": "example.com",
            "url": "https://example.com/story",
            "integrity_group_id": "SYNTHETIC_GROUP_001",
            "integrity_is_best": True,
            "ledger_decision": "passed",
            "editorial_bucket": "strict_passed_spec",
            "reason": "The production-start event satisfies the strict current-change contract.",
            "spec_id": spec["spec_id"],
            "merged_into_spec_id": None,
            "baseline_match": None,
            "baseline_relation": spec["baseline_relation"],
            "duplicate_risk": spec["duplicate_risk"],
            "staleness_decision": spec["staleness_decision"],
            "treasure_hunt_sampled": False,
            "notes": "Synthetic full-artifact regression fixture.",
            "anchor_classes": copy.deepcopy(spec["anchor_classes"]),
            "news_value_basis": "Production start materially advances the named product beyond roadmap status.",
            "structural_value_lenses": copy.deepcopy(spec["structural_value_lenses"]),
            "structural_value_override_applied": spec["structural_value_override_applied"],
            "structural_value_override_reason": spec["structural_value_override_reason"],
            "evidence_needed_for_stage_b": copy.deepcopy(spec["evidence_needed_for_stage_b"]),
            "why_execution_event_not_required": spec["why_execution_event_not_required"],
            "incremental_information": spec["incremental_information"],
            "decision_relevance": spec["decision_relevance"],
            "baseline_expectation_changed": spec["baseline_expectation_changed"],
            "follow_up_relation": spec["baseline_follow_up_relation"],
            "next_confirmation_points": copy.deepcopy(spec["next_confirmation_points"]),
            "portfolio_coverage_contribution": copy.deepcopy(spec["portfolio_coverage_contribution"]),
            "earnings_deep_dive_required": spec["earnings_deep_dive_required"],
            "qna_status": spec["qna_status"],
            "review_pool_subtype": None,
            "review_pool_repromotion_precondition": None,
            "decision_news_value_score": spec["decision_news_value_score"],
            "decision_value_breakdown": copy.deepcopy(spec["decision_value_breakdown"]),
            "decision_value_classification": spec["decision_value_classification"],
            "prior_state": spec["prior_state"],
            "new_verified_fact": spec["new_verified_fact"],
            "changed_judgment": spec["changed_judgment"],
            "uncertainty_resolved": spec["uncertainty_resolved"],
            "remaining_uncertainty": spec["remaining_uncertainty"],
            "denominator_used": spec["denominator_used"],
            "denominator_gap": spec["denominator_gap"],
            "publication_urgency": copy.deepcopy(spec["publication_urgency"]),
            "anti_bias_check": copy.deepcopy(spec["anti_bias_check"]),
            "structural_rescue_required": spec["structural_rescue_required"],
            "structural_rescue_question": spec["structural_rescue_question"],
            "technology_validation_stage": spec["technology_validation_stage"],
            "technology_score_cap_applied": spec["technology_score_cap_applied"],
            "technology_validation_gap": spec["technology_validation_gap"],
            "legal_policy_stage": "not_applicable",
        }

    def full_artifact(self):
        spec = self.full_spec()
        return {
            "stage": "stage_a",
            "run_tag": "SYNTHETIC_V3_FULL_ARTIFACT",
            "run_label": "Synthetic Stage A V3 full artifact",
            "source_prompt_file": self.SOURCE_PROMPT_FILE,
            "source_prompt_sha256": self.SOURCE_PROMPT_SHA256,
            "source_prompt_version": "structural_default_review_pool_partition_20260506",
            "source_prompt_authority": "uploaded_or_repo_source_file_prompt",
            "source_prompt_provenance_status": "PASS",
            "input_file": "synthetic_input.json",
            "baseline_file": "data/cards.full.json",
            "baseline_source_declaration": "Synthetic fixture representing current GitHub main baseline.",
            "baseline_count": 0,
            "github_main_sync_required_later": False,
            "source_universe": "synthetic one-story Stage A universe",
            "story_count": 1,
            "original_status_counts": {"kept": 1},
            "integrity_summary": {"status": "PASS"},
            "recommended_for": ["Stage B evidence package construction"],
            "stage_a_validity_status": "PASS",
            "artifact_consistency_status": "PASS",
            "csv_schema_status": "PASS",
            "review_pool_partition_status": "PASS",
            "strict_pass_gate_metadata_status": "PASS",
            "baseline_duplicate_screen_status": "PASS",
            "next_call_recommendation": {
                "recommended_next_call": "Stage B r0",
                "recommended_prompt_id": "Prompt 0.2",
                "recommended_input_universe": "Stage A strict_passed_spec[] only",
                "reason": "All Stage A safety gates pass and one strict candidate is available for evidence packaging.",
                "blocked_items_summary": [],
            },
            "required_docs_check": {
                "docs_expected": list(self.MANDATORY_DOCS),
                "docs_read_from_github_main": list(self.MANDATORY_DOCS),
                "docs_missing_or_unreadable": [],
                "status": "PASS",
            },
            "lane_sanity_rules_applied": ["selector_only_no_fetch"],
            "dropped_treasure_hunt": {
                "performed": False,
                "trigger_reason": "No dropped stories in the synthetic fixture.",
                "sample_strategy": "none_required",
                "sample_size": 0,
                "sampled_story_ids": [],
                "rescued_count": 0,
                "rescue_ids": [],
                "non_sampled_dropped_count": 0,
                "non_sampled_ledger_policy": "All synthetic stories are represented in the decision ledger.",
            },
            "summary": {
                "legacy_keep_count": 0,
                "strict_passed_spec_count": 1,
                "needs_review_count": 0,
                "rejected_count": 0,
                "existing_reinforcement_count": 0,
                "support_source_only_count": 0,
                "duplicate_or_reinforcement_count": 0,
                "stale_discarded_count": 0,
                "stale_warm_review_count": 0,
                "total_ledger_count": 1,
                "ledger_matches_story_count": True,
                "structural_selector_policy_version": "STRUCTURAL_NEWS_VALUE_SELECTION_V3",
                "structural_selector_policy_file": "docs/STRUCTURAL_NEWS_VALUE_SELECTION.md",
                "structural_selector_policy_sha": "synthetic-policy-sha",
                "credibility_cardability_value_urgency_separated": True,
                "industry_first_weighting_applied": True,
                "core_industrial_weight_total": 70,
                "multi_anchor_class_model_applied": True,
                "mandatory_structural_lenses_applied": True,
                "anchor_class_counts": {
                    "execution_event_anchor": 1,
                    "technology_commercialization_anchor": 1,
                },
                "structural_lens_coverage_counts": {"technology_transition_commercialization": 1},
                "decision_value_classification_counts": {"material_industry_signal": 1},
                "critical_structural_candidate_ids": [],
                "high_decision_value_candidate_ids": [],
                "high_value_review_pool_ids": [],
                "structural_signal_review_pool_ids": [],
                "earnings_deep_dive_pool_ids": [],
                "follow_up_candidate_ids": [],
                "zero_coverage_domains": [],
                "execution_or_formality_bias_findings": [],
                "technology_validation_gap_ids": ["SPEC_EXEC_ROUTE_001"],
                "legal_policy_stage_gap_ids": [],
                "search_before_delete_applied": True,
                "earnings_call_qna_rule_applied": True,
                "follow_up_probability_review_applied": True,
                "portfolio_coverage_audit_applied": True,
                "structural_value_selector_status": "PASS",
                "portfolio_coverage_audit_status": "PASS",
                "earnings_call_qna_audit_status": "NOT_APPLICABLE",
                "follow_up_repromotion_audit_status": "PASS",
                "execution_event_bias_audit_status": "PASS",
                "content_depth_audit_status": "PASS",
                "decision_ledger_count": 1,
            },
            "legacy_keep": [],
            "strict_passed_spec": [spec],
            "review_pool": [],
            "candidate_review_pool": [],
            "watchlist_context_pool": [],
            "reject_or_support_only_pool": [],
            "review_pool_partition_summary": {},
            "review_pool_carry_forward_ledger_status": "PASS",
            "review_pool_resolution_ledger": [],
            "rejected": [],
            "existing_reinforcement": [],
            "support_source_only": [],
            "dropped_treasure_hunt_result": [],
            "decision_ledger": [self.ledger_row(spec)],
        }